### ISSUE TITLE
Check Spelling

### ISSUE THREAD

**Issue by tiagoporto** [tiagoporto/swillboilerplate.rocks#1]

**Comment by ransty** [comment]
I've fixed a bunch of spelling mistakes and grammatical errors in README.md.

**Comment by luongthomas** [comment]
Hello I've got a pull request with proposed spelling and grammar changes.  Please let me know what you think about them.  I'm open to criticism so feel free to critique.  

#11

**Comment by luongthomas** [comment]
Were the changes satisfactory?

**Comment by tiagoporto** [comment]
Yes, thanks.
